### ISSUE TITLE
File structure not compatible with Lua's Busted tests

### ISSUE THREAD

**Issue by ryanford-frontend** [exercism/lua#223]
Busted expects a file structure like:

```
├── raindrops
│   ├── raindrops.lua
│   ├── README.md
│   └── spec
│       └── raindrops_spec.lua

```

Where the specs are is a `spec` folder. So when you run `busted` it will find the specs, else you will have to run `busted .`

Can the files come packaged like this?

**Comment by ryanplusplus** [comment]
We structured it as-is to simplify the directory structure. We should be able to have the simple structure and the ability to run tests with `busted` if we include a `.busted` configuration file at the root of each exercise. Would this meet your needs?

**Comment by ryanford-frontend** [comment]
Sounds great! :+1:
