### ISSUE TITLE
pig-latin: 2 incorrect tests

### ISSUE THREAD

**Issue by glennj** [exercism/lua#328]
I disagree with the multi-word tests, the last two in the spec file
- `what` should translate as `atwhay`
    ```lua
        assert.equal('ellway, hatway avehay eway erehay?', translate('well, what have we here?'))
        -- ...................^^^^^^
    ```
- `spaces` should translate as `acesspay`
    ```lua
        assert.equal('abstay\tanday   pacessay', translate('tabs\tand   spaces'))
        -- ...........................^^^^^^^^
    ```

These cases would fall into the ["some letter clusters are treated like a single consonant"](https://github.com/exercism/problem-specifications/blob/main/exercises/pig-latin/canonical-data.json#L105) class

**Comment by ryanplusplus** [comment]
The pig latin tests were based off of a really old version of the spec and that test no longer exists. https://github.com/exercism/lua/pull/329 updates pig latin to the latest spec and (hopefully) resolves any remaining issues.
