### ISSUE TITLE
Installing luarocks modules on Linux and Mac shouldn't use sudo

### ISSUE THREAD

**Issue by bushblade** [exercism/lua#353]
Currently the guide on [setting up Lua](https://exercism.org/docs/tracks/lua/installation)
States:-

> If this fails, you may need to use sudo:
> 
> ```$ sudo luarocks install busted```

Though I don't think this is a good idea.
You should only use sudo to install packages maintained by your distributions repositories in the root file system.
Instead of installing with root privileges I think it would be better to guide the user to install using the [luarocks](https://github.com/luarocks/luarocks/wiki/luarocks) `--local` flag which will install the module in the users home directory, then they will need to add the `~/.luarocks/bin` to their `$PATH`

**Comment by ryanplusplus** [comment]
Agreed. Can you create a PR that fixes this?
