### ISSUE TITLE
Add resistor-color-duo exercise

### ISSUE THREAD

**Issue by keiravillekode** [exercism/lua#396]
The `resistor-color-trio` exercise has already been implemented.

I would like to add the [`resistor-color`](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color) and [`resistor-color-duo`](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-duo) exercises.

**Comment by ryanplusplus** [comment]
Sure! Please do them in 2 separate PRs to make it easier to review and merge them quickly.
