### ISSUE TITLE
Port additional exercises

### ISSUE THREAD

**Issue by BNAndras** [exercism/lua#408]
I'd like to port the following exercises before the end of the month (unless you have other exercises in mind)

- [x] armstrong-numbers
- [x] darts
- [x] high-scores
- [x] pop-count
- [x] square-root
- [x] two-fer

**Comment by imolein** [comment]
That would be nice, thanks a lot in advance :)

**Comment by BNAndras** [comment]
I'll add high-scores this weekend to close this round of exercises.

**Comment by imolein** [comment]
Thank you :)
