### ISSUE TITLE
Fix: Copy and paste leftover in Queen-Attack

### ISSUE THREAD

**Issue by vaeng** [exercism/lua#417]
https://github.com/exercism/lua/blob/fe39d82d1418b390329d7c6210cbde9da1f92752/exercises/practice/queen-attack/queen-attack_spec.lua#L3

That might be an artifact from copying the exercise, right?

**Comment by imolein** [comment]
Most likely :)

Would you like to send a PR for this? Otherwise I'll fix it in a few hours when I have time.
