### ISSUE TITLE
High-scores has high cognitive load for new Lua users (mentoring feedback)

### ISSUE THREAD

**Issue by glennj** [exercism/lua#429]
High-Scores is quite early in the list of exercises. It's probably the first one to introduce colon notation and the idea of a function returning a table with functions. I've had a few mentoring sessions where the user was pretty lost.

I don't have any concrete suggestions at the moment. Some thoughts:

* add an introduction.md.append file to discuss:
  * closures and/or OOP in Lua
  * return values from modules
  * colon notation versus dot notation
* flesh out the stub file a bit
* move the exercise later in the list of exercises and/or bump the difficulty

**Comment by glennj** [comment]
Examples:

* https://exercism.org/mentoring/requests/71934aafebe9427db0e59257d59eb4b1
* https://discord.com/channels/854117591135027261/1181639884360912956 and the corresponding https://exercism.org/mentoring/requests/cc9f908f8dd34af5ba7b245a2cf08dce

**Comment by rudzik8** [comment]
I think this exercise should be moved to follow Binary Search. The difficulty can remain as long as there's a clear explanation of Lua OOP given and a clear set of requirements, like for other tasks. It shouldn't require you to read the testing code to understand what it even needs.

For example, I, when just stepping into this exercise, thought it just had to return 3 values: the highest score, the last added score and a sequence table containing the top 3 scores.

**Comment by ryanplusplus** [comment]
Thanks for the feedback. I'll flesh out the stub, bump the difficulty, and move it so that it comes after Binary Search.
