### ISSUE TITLE
There should be a guide on how to set up unit test debugging on the 'tracks/lua/resources' page.

### ISSUE THREAD

**Issue by edzillion** [exercism/lua#430]
[This page](https://exercism.org/docs/tracks/lua/resources) should include a guide on how to set up unit test debugging. I got by without this until I hit the `custom-set` exercise, in which case it would just be massively tedious to recreate the tests in code inside your module. I find a long or awkward process of setting up your dev enviroment to be quite demotivating, and I am sure there are many that would not have gone through the day and a half process it took me to get this set up. 

I wrote up a how-to on the forum, it's a little confusingly written so I could rewrite with simplified instructions, if this is a useful idea. I could also go through the linux setup, but I do not have a mac so I would need someone else to do that part. 

https://forum.exercism.org/t/how-to-debug-busted-unit-tests-in-vscode/8560

**Comment by ryanplusplus** [comment]
Please do, thanks!

**Comment by edzillion** [comment]
ok @ryanplusplus I wrote this up and tested on win 10 and ubuntu 20.04. Where should it be located though? My current draft is written in markup FWIW:

[<script src="https://gist.github.com/edzillion/8cf275d68fbba92dd1d4a028a6ca1171.js"></script>](https://gist.github.com/edzillion/8cf275d68fbba92dd1d4a028a6ca1171)

**Comment by imolein** [comment]
Hi, thanks for creating this guide :)

I would suggest to put it in docs/TESTS.md under a new headline like "Debugging unit tests" or something like this. 

I just saw that the README of **Local Lua Debugger** says it support Lua 5.1-5.3 and JIT. I would suggest to mention this also in the guide.

**Comment by edzillion** [comment]
> I just saw that the README of Local Lua Debugger says it support Lua 5.1-5.3 and JIT. I would suggest to mention this also in the guide.

Perhaps ... I hesitate because I have been using it just fine with 5.4 and I wonder has it just not been tested with that version? I say that because the [author of that plugin has stated that he does not have a lot of time to support the plugin](https://github.com/tomblind/local-lua-debugger-vscode/issues/80). In the interests of keeping thing simple I might just avoid stating compatibility at all.

**Comment by ryanplusplus** [comment]
This looks great, thanks!

**Comment by edzillion** [comment]
Great. I guess the obvious next suggestion is whether to put those debug lines to the top of each `test_spec.lua` file?

```lua
if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
  require("lldebugger").start()
end
```

**Comment by ryanplusplus** [comment]
> Great. I guess the obvious next suggestion is whether to put those debug lines to the top of each `test_spec.lua` file?
> 
> ```lua
> if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
>   require("lldebugger").start()
> end
> ```

I think that might look intimidating to someone who's just getting started, but I'd like to hear feedback from others.

**Comment by Ismoh** [comment]
I don't know exercism, but regarding local-lua-debugger you might can and want to adapt the launch.json from my current project:
[/.vscode/launch.json](https://github.com/Ismoh/NoitaMP/blob/133-if-you-do-it-quickndirty-your-code-quality-will-suffer/.vscode/launch.json#L29-L52)
