### ISSUE TITLE
Custom set question

### ISSUE THREAD

**Issue by elcarn23** [exercism/lua#433]
When I was doing the custom set exercise in the spec file on line 65 the prompt says that it should indicate that it is not disjoint but the test itself is trying to assert true that a set is indeed disjoint with an empty set.  Shouldn't that be checking for false indicating that it is not disjoint?  I'm sorry if this is a silly question.  I'm happy to update the spec file if we want to be checking that it is false.

**Comment by ryanplusplus** [comment]
Sorry for the delay looking at this. It looks like you're right and the test name is messed up. Will you make a PR to update the spec to fix this?

**Comment by elcarn23** [comment]
Sure I've created a PR and it closed it immediately -- https://github.com/exercism/lua/pull/437.  I had opened the topic on the forum as well -- https://forum.exercism.org/t/lua-track-custom-set-exercise/9086.  They had updated the problem set code as well.

**Comment by elcarn23** [comment]
Just saw that you re-opened it.  I guess I should have waited a moment.  Thanks for the chance to contribute even a little to the platform.
