### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/lua#501]
@keiraville You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by iHiD** [comment]
(cc @keiravillekode - I got your username wrong before sorry!)

**Comment by keiravillekode** [comment]
Yes, I would be happy to join the Lua maintainers.

**Comment by ryanplusplus** [comment]
Thanks @keiravillekode!

**Comment by imolein** [comment]
What is the current workflow to add a new maintainer? When @ryanplusplus asked me back then, I had to make a PR adding myself to a maintainer.json file, but this no longer exists as far as I can see.

**Comment by glennj** [comment]
I _think_ it's adding a person to the exercism/lua team, which needs privs in the exercism org.

**Comment by ErikSchierboom** [comment]
> I think it's adding a person to the exercism/lua team, which needs privs in the exercism org.

That is correct!

**Comment by ErikSchierboom** [comment]
@keiravillekode Awesome. Thank you!

You're part of the team now. You also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
